title: Quinise Ercolano
description: Full Stack Software Developer

markdown: kramdown
permalink: pretty

github:
  is_project_page: false

# Apply default layout to all pages
defaults:
  - scope: { path: "" }
    values: { layout: default }

# user site settings
url: https://quinise.github.io
baseurl: ""
